blogresume/blog_posts/forms.py
#blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = StringField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

blogresume/blog_posts/views.py
#blog_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from blogresume import db
from blogresume.models import BlogPost
from blogresume.blog_posts.forms import BlogPostForm


blog_posts = Blueprint('blog_posts', __name__)

#create
@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()

        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)
#view
#int forces the post to be treated as an integer, not a string
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_posts.html', title=blog_post.title, date=blog_post.date, post=blog_post)

#update
#int forces the post to be treated as an integer, not a string
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text= form.text.data
        db.session.commit()

        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Updating', form=form)

#delete
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
            abort(403)

    db.session.delete(blog_post)
    db.session.commit()

    return redirect(url_for('core.index'))

blogresume/core/views.py
# core/views.py
from flask import render_template, redirect, request, Blueprint, url_for
from flask_login import login_user
from blogresume.models import User, BlogPost
from blogresume.users.forms import RegistrationForm, LoginForm
from blogresume import db

core = Blueprint('core', __name__)


@core.route('/', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    
    #built-in registration on homepage
    form = RegistrationForm()
    loginForm = LoginForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    elif loginForm.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('index.html', blog_posts=blog_posts, form=form, loginForm=loginForm)


@core.route('/info')
def info():
    return render_template('info.html')

blogresume/users/views.py
#users/view.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blogresume import db
from blogresume.models import User, BlogPost
from blogresume.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from blogresume.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

#register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Thanks for registering")
        return redirect(url_for('users.login'))
    return form
#login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)           
    return render_template('login.html', form=form)

#logout
@users.route('/route')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

#account (update UserForm)
@users.route('/account',methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.profile_pic.data:
            username = current_user.username
            pic = add_profile_pic(form.profile_pic.data, username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Updated!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

#show blog posts
@users.route("/<username>", methods=['GET', 'POST'])
def user_post(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

blogresume/templates/account.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <div align='center'>
        <h1>welcome {{current_user.username}}!</h1>
        <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
    </div>
</div>
<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.username.label(class='form-group')}}
            {{form.username(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.email.label(class='form-group')}}
            {{form.email(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.profile_pic.label(class='form-group')}}
            {{form.profile_pic(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
        

    </form>
</div>   


{% endblock %}

blogresume/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/custom.css') }}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.js" integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title>Wayne Bryant</title>
</head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
            <a class="navbar-brand abs" style="font-weight: bold" href="{{url_for('core.index')}}">Wayne Bryant</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="collapsingNavbar">
                <ul class="navbar-nav">

                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('core.info')}}">About</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('core.info')}}">Engage</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li>
                </ul>
            </div>
        </nav>
      
<div class="container-fluid">
    {% block content %}

    {% endblock %}
</div>
    </body>


</html>

blogresume/templates/blog_post.html
{% extends "base.html" %}

{% block content %}
    <div class="jumnbotron">
        <h1>{{title}}</h1>
        <h2>Written by: {{post.author.username}}</h2>
        <h3>Published: {{date.strftime('%B %d, %Y')}}</h3>
        <p>{{post.text}}</p>
        {% if post.author == current_user %}
            <div>
                <a href="{{url_for('blog_posts.update_post', blog_post_id=post.id)}}">Update</a>
                <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
            </div>
        {% endif %}
    </div>    
    <div class="modal" tabindex="-1" role="dialog" id="del_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this blog post?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{{url_for('blog_posts.delete_post', blog_post_id=post.id)}}">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

blogresume/templates/blog_posts.html
{% extends "base.html" %}

{% block content %}
    <div class="jumnbotron">
        <h1>{{title}}</h1>
        <h2>Written by: {{post.author.username}}</h2>
        <h3>Published: {{date.strftime('%B %d, %Y')}}</h3>
        <p>{{post.text}}</p>
        {% if post.author == current_user %}
            <div>
                <a href="{{url_for('blog_posts.update_post', blog_post_id=post.id)}}">Update</a>
                <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
            </div>
        {% endif %}
    </div>    
    <div class="modal" tabindex="-1" role="dialog" id="del_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this blog post?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{{url_for('blog_posts.delete_post', blog_post_id=post.id)}}">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

blogresume/templates/create_post.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form method="POST" >
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.title.label(class='form-control-label')}}
                {{form.title(class='form-control form-control-lg')}}
            </div>
            <div class="form-group">
                {{form.text.label(class='form-control-label')}}
                {{form.text(class='form-control form-control-lg')}}
            </div>
            <div class="form-group">
                {{form.submit(class='btn btn-outline-info')}}
            </div>
    </div>    


{% endblock %}

blogresume/templates/index.html
{% extends "base.html" %}

{% block content %}
<br />
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8">
            <img src="{{url_for('static',filename='website_pics/landing_background2.jpg')}}" class="img-fluid" alt="Responsive image" />
        </div>
    </div>
</div>
<br />


<h2 class="text-center text-primary">Blog Posts</h2>
<div class="container">
    {% for post in blog_posts.items %}
    <div class="card" style="width: 67.5rem;">
        <div class="card-body">
            <h2><a class="card-title" href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a></h2>
            <p>
                {% if post.text|length > 100 %}
                {{post.text[:100]}}...
                {% else %}
                {{post.text[:100]}}
                {% endif %}
            </p>

            <p>
                Written by: <a href="{{url_for('users.user_post', username=post.author.username)}}">{{post.author.username}}</a>
                <span style="float:right">Published on: {{post.date.strftime('%m-%d-%Y')}}</span>
            </p>
        </div>
    </div>
    <br />
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endblock %}

blogresume/templates/info.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid mt-1">
    <div class="row">
        <div class="col-xl-6 mr-0">
            <img src="{{url_for('static',filename='website_pics/WayneBryantGarden.jpg')}}" class="img-fluid " alt="Responsive image" />
        </div>
        <div class="jumbotron vert-center col-xl-6">
            <div class="d-flex flex-column">
                <div>
                    <h1>Wayne Bryant</h1>
                </div>
                <div>
                    <p>
                        Wayne Bryant is a problem-solving enthusiast who loves to dive headfirst into complex problems, develop creative solutions, 
                        and drive results for senior leadership. He is currently working as a Senior Wealth & Asset Management Consultant for 
                        Ernst & Young with a focus on digital platforms.
                    </p>
                    <br />
                    Wayne has been enamored with technology every since he built his first PC at the age of 8, which ultimately led to 
                    his double major in Computer Science and Business Management. Wayne built this website as a medium to express his personal views 
                    and explore of the interconnectivity between business and technology.
                </div>
            </div> 
        </div>

    </div>
</div>



{% endblock %}

blogresume/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.submit()}}
    </form>

{% endblock %}

blogresume/templates/register.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.username.label}}{{form.username}}<br>
        {{form.email.label}}{{form.email}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.password_confirm.label}}{{form.password_confirm}}<br>
        {{form.submit()}}
    </form>

{% endblock %}

blogresume/templates/user_blog_posts.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <div align='center'>
            <h1>Welcome to the blogpage for {{user.username}}</h1>
            <img src="{{url_for('static', filename='profile_pics/'+user.profile_image)}}">
        </div>
    </div>
    
{% for post in blog_posts.items %}
     <div class="card" style="width: 40rem;">
        <div class="card-body">
            <h2><a class="card-title" href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a></h2>
            <div class="card-body">{{post.text}}</div>
            Written by: 
            <a href="{{url_for('users.user_post', username=post.author.username)}}">{{post.author.username}}</a>
            <p>Published on: {{post.date.strftime('%m-%d-%Y')}}</p>
            <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">Read Blog Post</a>
        </div>
    </div>  


    <br>
{% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
         {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2) %}
            {% if blog_posts.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('users.user_post', username=user.username, page=page_num)}}">{{page_num}}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('users.user_post', username=user.username, page=page_num)}}">{{page_num}}</a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endblock %}